### ISSUE TITLE
Exception thrown on startup.

### ISSUE THREAD

**Issue by Trqhxrd** [WolfyScript/WolfyUtilities#90]
**Describe the bug**
I just installed the spigot plugin and it threw this error:
```
[11:54:41 ERROR]: [CustomCrafting] Could not load item 'customcrafting:customcrafting/recipe_book':
[11:54:41 WARN]: me.wolfyscript.lib.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `me.wolfyscript.utilities.api.inventory.custom_items.references.APIReference` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
[11:54:41 WARN]:  at [Source: (File); line: 2, column: 20] (through reference chain: me.wolfyscript.utilities.api.inventory.custom_items.CustomItem["apiReference"])
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:274)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3494)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader.lambda$loadItemsInNamespace$0(LocalStorageLoader.java:117)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader$NamespaceFileVisitor.visitFile(LocalStorageLoader.java:358)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader$NamespaceFileVisitor.visitFile(LocalStorageLoader.java:346)
[11:54:41 WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2812)
[11:54:41 WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2883)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader.readFiles(LocalStorageLoader.java:133)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader.loadItemsInNamespace(LocalStorageLoader.java:113)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader.load(LocalStorageLoader.java:74)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.ResourceLoader.load(ResourceLoader.java:65)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.DataHandler.load(DataHandler.java:114)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.DataHandler.loadRecipesAndItems(DataHandler.java:124)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.CustomCrafting.onEnable(CustomCrafting.java:310)
[11:54:41 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:54:41 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:54:41 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[11:54:41 WARN]: 	at GrapesRPG-1.0-SNAPSHOT.jar//me.trqhxrd.grapesrpg.GrapesRPG$Companion.downloadDependencies(GrapesRPG.kt:144)
[11:54:41 WARN]: 	at GrapesRPG-1.0-SNAPSHOT.jar//me.trqhxrd.grapesrpg.GrapesRPG$Companion.init(GrapesRPG.kt:75)
[11:54:41 WARN]: 	at GrapesRPG-1.0-SNAPSHOT.jar//me.trqhxrd.grapesrpg.Main.onEnable(Main.kt:26)
[11:54:41 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:54:41 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:54:41 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[11:54:41 WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[11:54:41 WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[11:54:41 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[11:54:41 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[11:54:41 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[11:54:41 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[11:54:41 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[11:54:41 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:54:41 ERROR]: [CustomCrafting] ----------------------
[11:54:41 ERROR]: [CustomCrafting] Could not load item 'customcrafting:customcrafting/advanced_crafting_table':
[11:54:41 WARN]: me.wolfyscript.lib.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `me.wolfyscript.utilities.api.inventory.custom_items.references.APIReference` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
[11:54:41 WARN]:  at [Source: (File); line: 2, column: 20] (through reference chain: me.wolfyscript.utilities.api.inventory.custom_items.CustomItem["apiReference"])
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:274)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
[11:54:41 WARN]: 	at wolfyutils-spigot-4.16.0.0.jar//me.wolfyscript.lib.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3494)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader.lambda$loadItemsInNamespace$0(LocalStorageLoader.java:117)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader$NamespaceFileVisitor.visitFile(LocalStorageLoader.java:358)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader$NamespaceFileVisitor.visitFile(LocalStorageLoader.java:346)
[11:54:41 WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2812)
[11:54:41 WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2883)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader.readFiles(LocalStorageLoader.java:133)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader.loadItemsInNamespace(LocalStorageLoader.java:113)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.LocalStorageLoader.load(LocalStorageLoader.java:74)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.ResourceLoader.load(ResourceLoader.java:65)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.DataHandler.load(DataHandler.java:114)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.handlers.DataHandler.loadRecipesAndItems(DataHandler.java:124)
[11:54:41 WARN]: 	at customcrafting-spigot-3.16.3.3.jar//me.wolfyscript.customcrafting.CustomCrafting.onEnable(CustomCrafting.java:310)
[11:54:41 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:54:41 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:54:41 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[11:54:41 WARN]: 	at GrapesRPG-1.0-SNAPSHOT.jar//me.trqhxrd.grapesrpg.GrapesRPG$Companion.downloadDependencies(GrapesRPG.kt:144)
[11:54:41 WARN]: 	at GrapesRPG-1.0-SNAPSHOT.jar//me.trqhxrd.grapesrpg.GrapesRPG$Companion.init(GrapesRPG.kt:75)
[11:54:41 WARN]: 	at GrapesRPG-1.0-SNAPSHOT.jar//me.trqhxrd.grapesrpg.Main.onEnable(Main.kt:26)
[11:54:41 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:54:41 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:54:41 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[11:54:41 WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[11:54:41 WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[11:54:41 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[11:54:41 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[11:54:41 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[11:54:41 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[11:54:41 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[11:54:41 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
1. Download and install the plugin
2. Start the server
3. See error

**Server (please complete the following information):**
 - Paper
 - 1.18.2
 - Java 18

**Comment by WolfyScript** [comment]
Can you update to WolfyUtilities 4.16.1.0 and try it again? 
https://github.com/WolfyScript/WolfyUtils-Spigot/releases/tag/v4.16.1.0

I think that should fix it.

**Comment by Trqhxrd** [comment]
I just checked it only happens on first run also.

**Comment by Trqhxrd** [comment]
Just tried the new version and it still happens.
But also still only on the first run. 
I used the version from your maven repo.

**Comment by WolfyScript** [comment]
In this log, it only affects the default recipes. Are other recipes affected by that error too?

**Comment by Trqhxrd** [comment]
Sorry for answeeing this late... I never added any so I don't know... In the end I made my own GUI since I plan on adding more slots for upgrades and so on

**Comment by Harsh-7821** [comment]
same thing error on startup but different error
```

[06:38:54] [Server thread/ERROR]: Fatal error trying to convert WolfyUtilities v4.16.3.0:com/wolfyscript/utilities/bukkit/WolfyCoreBukkit.class
--
17 | java.lang.IllegalArgumentException: Unsupported class file major version 60
18 | at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196) ~[minecraft_server.jar:git-Paper-189]
19 | at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:177) ~[minecraft_server.jar:git-Paper-189]
20 | at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:163) ~[minecraft_server.jar:git-Paper-189]
21 | at org.bukkit.craftbukkit.v1_16_R2.util.Commodore.convert(Commodore.java:171) ~[minecraft_server.jar:git-Paper-189]
22 | at org.bukkit.craftbukkit.v1_16_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:314) ~[minecraft_server.jar:git-Paper-189]
23 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144) ~[minecraft_server.jar:git-Paper-189]
24 | at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[minecraft_server.jar:git-Paper-189]
25 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[minecraft_server.jar:git-Paper-189]
26 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[minecraft_server.jar:git-Paper-189]
27 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_342]
28 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_342]
29 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_342]
30 | at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_342]
31 | at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[minecraft_server.jar:git-Paper-189]
32 | at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[minecraft_server.jar:git-Paper-189]
33 | at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[minecraft_server.jar:git-Paper-189]
34 | at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[minecraft_server.jar:git-Paper-189]
35 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[minecraft_server.jar:git-Paper-189]
36 | at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[minecraft_server.jar:git-Paper-189]
37 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[minecraft_server.jar:git-Paper-189]
38 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[minecraft_server.jar:git-Paper-189]
39 | at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]

<!--EndFragment-->
</body>
</html>[06:38:54] [Server thread/ERROR]: Fatal error trying to convert WolfyUtilities v4.16.3.0:com/wolfyscript/utilities/bukkit/WolfyCoreBukkit.class
java.lang.IllegalArgumentException: Unsupported class file major version 60
	at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:[17](https://aternos.org/log/#L17)7) ~[minecraft_server.jar:git-Paper-[18](https://aternos.org/log/#L18)9]
	at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:163) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_16_R2.util.Commodore.convert(Commodore.java:171) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_16_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:314) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[minecraft_server.jar:git-Paper-189]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_342]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_342]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_342]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_342]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[minecraft_server.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[minecraft_server.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:[20](https://aternos.org/log/#L20)8) ~[minecraft_server.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[minecraft_server.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[minecraft_server.jar:git-Paper-189]

```
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_[34](https://aternos.org/log/#L34)2]
